# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6b554f8881a4098bda0437d6600e1d4d804b39956695f5b676de8e9ee749ba0a215ea2011ac694eccb5a7c529519daa132043c314c574e43059abe09e67e951

test:
  secret_key_base: 19eeba59b1629e79e99300fb756710070380ca9cc2f2fc5b0c58fd2824b80615031f5280de7445a32808cea139f03dea8d7fc9f2c7c3bdd4c2c11065928ca9bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
